---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "demo02"
  spec:
    tags:
    - from:
        kind: "ImageStreamImage"
        name: "demo02@sha256:65955c8d496929ed80dbf7a6bc748417a0595be08ef0a11a8e95977654f48365"
        namespace: "myservices"
      name: "1.0"
